version: 0.2

phases:
  post_build:
    commands:
      - mvn package
      - aws cloudformation package --template-file Tracker.yaml --output-template-file serverless-output.yaml --s3-bucket ktka-cloudformation-tracker
artifacts:
  files:
    - target/tracker-1.0-SNAPSHOT.jar
    - serverless-output.yaml